### PR TITLE
 Added ObjectID type as session guard and unguard

### PR DESCRIPTION
**Pull request by juampi92**
Now it will take advantage of MongoDB's Object IDs for storing IDs in the session.

### CODE REVIEW

**Comment by juampi92** [comment]
Sorry for not using develop branch 😬

**Comment by RomainLanz** [comment]
Hey @juampi92! 👋 

Could you please retarget the develop branch?

**Comment by juampi92** [comment]
Done! Thanks @RomainLanz

**Comment by juampi92** [comment]
Hi. Sorry to bother.
How's the status of this? @thetutlage @RomainLanz

**Comment by thetutlage** [comment]
Can u please explain what is `objectId`? and why it has to be part of data type. Can you just not store the id in the session and when you get it, simply wrap it inside the `objectid` function?

**Comment by juampi92** [comment]
In my project I ended up casting as a String the ObjectId, which is what happens when you try to store it, but for some reason you do this type casting manually, so if I let the Session Store do that for me it'd throw that the ObectId is not a valid type.

Each mongodb document has a unique _id value that's an [ObjectId](https://docs.mongodb.com/manual/reference/method/ObjectId/). It's also an index, so it's the base identifier.

I was storing the full user object (_id, username, password, email) on the session, and it'd use the primarKey (_id) to store it, so when the Session Store checked the type of what's being stored, it'd fail.

**Comment by thetutlage** [comment]
I am trying to get my head around it. So please bear with me :)

So you have a user, which has an Id and that id is of type `ObjectId`.

If above statement is correct, it should work fine, since the session store only cast the top level node, which is the `user` object in your case.

Now the main question is, is `ObjectId` `JSON.stringify` friendly or not?

**Comment by juampi92** [comment]
ObjectId is stringifiable, yes. But that's not the issue.

Let me take Adonis-auth as an example. The Session Scheme. 
This line says that it stores into the session the primaryKeyValue. [Schemes/Session.js:L215](https://github.com/adonisjs/adonis-auth/blob/develop/src/Schemes/Session.js#L215) 

If you look at the base primaryKeyValue accessor, you get that this extracts the primaryKey from the instanceUser. NOT the full user, just the user's id field. And that's an ObjectId
[Schemes/Base.js:85](https://github.com/adonisjs/adonis-auth/blob/develop/src/Schemes/Base.js#L85)

I ended up adding another accessor to the user primaryKey that returns the ObjectId casted as a String, but the thing is that it shouldn't throw an error the Session; the session itself should cast it into a String.

And that's why I did this PR. 😅

**Comment by thetutlage** [comment]
I didn't got much time to look into this PR. After reviewing carefully and reading about the `objectId`. I am happy to approve it.

Can you please rebase it with the develop branch?

**Pull request merged**
